# Generated by Django 5.0.3 on 2024-04-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_from', models.DateField(verbose_name='Travel From')),
                ('date_to', models.DateField(verbose_name='Travel To')),
                ('location', models.CharField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
