# Generated by Django 5.0.3 on 2024-04-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_itinerary_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.itinerary')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
