# Generated by Django 5.0.4 on 2024-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(default='main_app/static/css/default.png', upload_to=''),
        ),
    ]
