# Generated by Django 5.0.4 on 2024-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_attraction_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='attraction',
        ),
        migrations.AddField(
            model_name='list',
            name='attractions',
            field=models.ManyToManyField(to='main_app.attraction'),
        ),
    ]
