# Generated by Django 5.0.4 on 2024-04-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_list_attraction_list_attractions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='attractions',
            new_name='attraction',
        ),
    ]
