# Generated by Django 5.0.4 on 2024-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_attractions_list_attraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='attraction',
            new_name='attractions',
        ),
    ]
