# Generated by Django 5.0.4 on 2024-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_attraction_list_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='attractions',
            field=models.ManyToManyField(to='main_app.attraction'),
        ),
    ]
