# Generated by Django 5.0.3 on 2024-04-12 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_itinerary_attractions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='attraction',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 18, 36, 7, 4062)),
        ),
        migrations.AddField(
            model_name='attraction',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 12, 18, 36, 7, 4072)),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
