# Generated by Django 5.0.3 on 2024-04-12 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_attraction_options_attraction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 18, 45, 20, 234011)),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 12, 18, 45, 20, 234027, tzinfo=datetime.timezone.utc)),
        ),
    ]
