# Generated by Django 5.0.3 on 2024-04-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_attraction_date_alter_attraction_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={},
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='time',
        ),
    ]
